feat: add Convert2Standard class
redcarrot1/JayangSageori pull request #3
Opened 2022-10-08 08:14 UTC by webb-c

## 요약
> 프로그램에서 인자로 전달받는 데이터 요소들을 표준형식으로 변환하는 클래스를 추가하였습니다.

<br>

## 작업 내용
- Convert2Standard 클래스는 각 명령어의 인자를 벡터형식으로 전달받아 검사하고 표준형식으로 변환해줍니다.
- 각각의 데이터 요소를 변경하는 함수는 private로 선언되어있습니다.
- 사용자는 기능 클래스 내부에서 Conver2Standard class에 접근하여 static 멤버 메소드를 호출하여 인자 표준형식 변환에 사용합니다. 
- 메소드는 발생한 예외를 모두 던지기 때문에, 함수를 호출하면 반드시 예외를 처리할 수 있도록 try{}catch{}를 사용해야합니다.

2022-10-08 15:09 UTC, redcarrot1 requested changes
vector<string> 인자 받을 때, 명령어까지 포함해서 받으면 어떨까요.

사용자가 입력한 string을 split으로 분리하면, (명령어와 인자)가 담긴 vector가 반환됩니다.
여기서 표준형식으로 변환하기 위해 Convert를 호출하려면, 명렁어(인덱스0)을 버리기 위해, 새로운 vector를 생성한 뒤 반환해야 합니다. 모든 사용자 명령에 적용되는 이야기라서, Convert 클래스에서 한 번에 처리해주시면 좋을 것 같습니다.

2022-10-09 00:57 UTC, webb-c commented
아 그러면 그냥 클래스 안에서 명령어가 유효한지에 대한 확인도 진행한 뒤 해당 명령어에 대한 인자 변환 메소드도 알아서 호출할 수 있도록 만들겠습니다.
그럼 Convert2Standard 클래스의 메소드가 표준형식이 담긴 결과벡터를 반환할때도 가장 앞에는 표준 형태의 명령어(=소문자)를 포함해서 반환하고, 호출한 위치에서 벡터의 첫번째 요소만 읽은 뒤 각 기능 클래스 함수를 호출하는 흐름도로 생각하면 될까요?

2022-10-09 08:25 UTC, redcarrot1 commented
네 맞습니다. 근데 `convert`에서 (명령어 변환, 명령어 파악 후 인자변환)을 다 수행하지 말고, 좀 쪼개도 괜찮을 것 같습니다.
사실 제가 생각한건 아래 코드같이 기능별로 쪼개는 거였는데, 이 부분은 자율적으로 하시면 될것 같습니다.

```c++
vector<string> command = Parsing::split("book 19 234");
if (command.size() == 0); // Exception

validCommand(command[0]); // 이 프로그램에서 지원하는 명령어인가?

if(command=="signin") {
    if(command.size()!=3) // Exception
    string name = convertName(command[1]);
    string phone = convertPhone(command[2]);
    // ... logic ...
}
else if(command=="signup") {
   ...
}
else {
    // Exception. 현재 명령창에서 사용 가능한 명령어가 아닙니다.
}
```

2022-10-09 23:13 UTC, webb-c commented
_수정해서 다시 커밋했습니다._

### 요약
> 명령어에 대해 형식을 검사하고, 표준명령어(소문자)로 변환시켜주는 메소드 추가

2022-10-10 01:56 UTC, redcarrot1 approved these changes

2022-10-10 01:56 UTC, merged